Implement GlobalExceptionHandler
FIAP-SOAT7-2024-GP-Kotlin/myburgercontrol-monolith pull request #24
Opened 2024-05-18 00:08 UTC by luizcalazans16

Implements GlobalExceptionHandler
Implements ReasonCode enum to provide a better way to control business, third-party and unexpected errors
Implement ReasonCodeException in order to have a generic way to throw Exceptions and handle them
Add customer creation validation
Add some integration and unit tests

2024-05-18 00:49 UTC, AndrePosTech approved these changes

2024-05-18 15:23 UTC, rafaeljpc requested changes

2024-05-18 15:23 UTC, rafaeljpc commented on src/main/kotlin/io/github/soat7/myburguercontrol/infrastructure/common/GlobalExceptionHandler.kt
> +            ErrorResponse(error.code, error.messages)
porque nao usar o ProblemDetail do springboot

https://deviniciative.wordpress.com/2023/02/17/spring-boot-3-melhorando-suas-exceptions-com-problem-details/

2024-05-18 20:04 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/infrastructure/common/GlobalExceptionHandler.kt
> +            ErrorResponse(error.code, error.messages)
Ajustado

2024-05-19 04:14 UTC, rafaeljpc approved these changes

2024-05-19 04:14 UTC, merged