Feature/jwt
FIAP-SOAT7-2024-GP-Kotlin/myburgercontrol-monolith pull request #25
Opened 2024-05-18 21:24 UTC by jsantosrocha

jwt and spring security implementation
added /user and /auth routes

2024-05-18 21:41 UTC, jsantosrocha commented
jwt and spring security implementation
added as /user and /auth routes

2024-05-19 04:20 UTC, rafaeljpc requested changes

2024-05-19 04:20 UTC, rafaeljpc commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/model/Enum.kt
> +    USER,
quais são os perfis de acesso do sistema?
só admin e user? não era pra ser Customer, Kitchen e Admin?

2024-05-19 04:20 UTC, rafaeljpc commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/model/User.kt
esse User é o mesmo user da role?

2024-05-19 06:29 UTC, jsantosrocha commented
Isso mesmo coloquei somente dois para os testes, mas está correto. Dá pra
controlar as rotas pela Role.
Como tem muita coisa em desenvolvimento forem adicionando as rotas vai
complementando e alterando os filtros.

Em dom., 19 de mai. de 2024 01:20, Rafael Correia ***@***.***>
escreveu:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/main/kotlin/io/github/soat7/myburguercontrol/domain/model/Enum.kt
> <https://github.com/FIAP-SOAT7-2024-GP-Kotlin/myburgercontrol-monolith/pull/25#discussion_r1605941252>
> :
>
> > @@ -0,0 +1,6 @@
> +package io.github.soat7.myburguercontrol.domain.model
> +
> +enum class Role {
> +    USER,
>
> quais são os perfis de acesso do sistema?
> só admin e user? não era pra ser Customer, Kitchen e Admin?
> ------------------------------
>
> On src/main/kotlin/io/github/soat7/myburguercontrol/domain/model/User.kt
> <https://github.com/FIAP-SOAT7-2024-GP-Kotlin/myburgercontrol-monolith/pull/25#discussion_r1605941382>
> :
>
> esse User é o mesmo user da role?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FIAP-SOAT7-2024-GP-Kotlin/myburgercontrol-monolith/pull/25#pullrequestreview-2064988466>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABUSBY7TORK5AHZ4RMAHEG3ZDASB7AVCNFSM6AAAAABH5YQLGGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRUHE4DQNBWGY>
> .
> You are receiving this because you were assigned.Message ID:
> <FIAP-SOAT7-2024-GP-Kotlin/myburgercontrol-monolith/pull/25/review/2064988466
> @github.com>
>

2024-05-19 13:36 UTC, jsantosrocha commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/model/Enum.kt
> +    USER,
Isso mesmo coloquei somente dois perfis, USER e ADMIN, para os testes. Dá pra controlar as rotas pela Role. Como tem muita coisa em desenvolvimento, conforme forem adicionando as rotas vai complementando e alterando os filtros

2024-05-19 13:38 UTC, jsantosrocha commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/model/User.kt
Não, ele guarda informação do usuário que acessou, inclusive a Role

2024-05-19 19:33 UTC, rafaeljpc approved these changes

2024-05-19 19:33 UTC, merged