Fix/jwt
FIAP-SOAT7-2024-GP-Kotlin/myburgercontrol-monolith pull request #29
Opened 2024-05-22 02:42 UTC by jsantosrocha

lint and jwt

2024-05-22 20:36 UTC, FlorencioF approved these changes

2024-05-23 01:20 UTC, luizcalazans16 requested changes

2024-05-23 01:20 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/service/UserService.kt
>          if (founded != null) {
Typo. O correto é found

2024-05-23 01:20 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/service/UserService.kt
>      private val dataBasePort: UserDatabasePort,
database

2024-05-23 02:08 UTC, jsantosrocha commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/service/UserService.kt
>          if (founded != null) {
ajustado

2024-05-23 02:08 UTC, jsantosrocha commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/service/UserService.kt
>      private val dataBasePort: UserDatabasePort,
ajustado

2024-05-23 14:50 UTC, luizcalazans16 approved these changes

2024-05-23 14:50 UTC, merged