feature/payment-integration
FIAP-SOAT7-2024-GP-Kotlin/myburgercontrol-monolith pull request #8
Opened 2024-05-14 00:08 UTC by FlorencioF

2024-05-14 00:10 UTC, FlorencioF commented
Ainda sem os testes unitários, mas já quero a validação/critica de voces

2024-05-15 23:30 UTC, luizcalazans16 requested changes

2024-05-15 23:30 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/application/ports/inbound/PaymentServiceUseCase.kt
> +interface PaymentServiceUseCase {
Alterar o nome para PaymentServicePort

2024-05-15 23:30 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/infrastructure/outbound/rest/feign/PaymentIntegrationFeignClient.kt
> +@FeignClient(name = "PaymentIntegrationFeignClient", url = "\${spring.feign.payment_integration_url}")
eu usaria o `RestTemplate` ao invés do `Feign`. Com isso, temos um maior controle da request como um todo e podemos manipular melhor a response.

2024-05-15 23:30 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/service/PaymentService.kt
> +    override fun requestPayment(payment: Payment): Payment {
enter

2024-05-15 23:30 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/model/Payment.kt
> +    enum class Status(){
colocar dentro do folder de `enum`

2024-05-15 23:30 UTC, luizcalazans16 commented on build.gradle.kts
> +    implementation("org.springframework.cloud:spring-cloud-starter-openfeign:4.1.1")
Remover caso a gente decida usar o `RestTemplate`

2024-05-16 00:40 UTC, FlorencioF commented on src/main/kotlin/io/github/soat7/myburguercontrol/application/ports/inbound/PaymentServiceUseCase.kt
> +interface PaymentServiceUseCase {
Feito

2024-05-20 12:39 UTC, AndrePosTech approved these changes

2024-05-22 21:40 UTC, luizcalazans16 requested changes

2024-05-22 21:40 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/domain/service/PaymentService.kt
> +    companion object : KLogging()
Colocar como private

2024-05-22 21:40 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/infrastructure/external/PaymentIntegrationService.kt
> +                    throw RuntimeException()
Usar ReasonCodeException

2024-05-22 21:40 UTC, luizcalazans16 commented on src/main/kotlin/io/github/soat7/myburguercontrol/infrastructure/external/PaymentIntegrationService.kt
> +            else throw RuntimeException()
ReasonCodeException

2024-05-22 21:40 UTC, luizcalazans16 commented on src/main/resources/application.yml
> +  feign:
Não precisa mais dessa property dado que mudamos para RestTemplate

2024-05-22 22:04 UTC, luizcalazans16 approved these changes

2024-05-22 22:05 UTC, merged